config/routes.rb
Rails.application.routes.draw do

root to:'homes#top'

  namespace :admin do
    resources :users, only:[:index]
  end
  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end

  namespace :public do
    resources :users, only:[:show,:edit,:update,:destroy]do
      member do
    get :likes
    end
      get :search, on: :collection
      resource :relationships, only: [:create, :destroy]
        get :followings, on: :member
        get :followers, on: :member
end
end

  namespace :public do
    resources :posts, only:[:index,:new,:create,:destroy, :show]do
      resource :likes, only: [:create, :destroy]
        resources :comments, only:[:create,:destroy]
          collection do
            get 'search'
          end
    end
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>leica</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
   <nav class="navbar navbar-expand-lg navbar-white bg-white">
  <div class="container">
 <div class="collapse navbar-collapse" id="navbarNavDropdown">
  <ul class="navbar-nav ml-auto">


<% if admin_signed_in? %>
 <li class="nav-item">
  <%= link_to admin_users_path, class: 'nav-link text-dark' do %>
   <button class="btn btn-md btn-light" type="submit">
    会員一覧
   </button>
  <% end %>
 </li>
 <li class="nav-item">
  <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
   <button class="btn btn-md btn-light" type="submit">
    ログアウト
   </button>
  <% end %>
 </li>
 <% end %>

<% unless admin_signed_in? %>
 <li class="nav-item">
  <%= link_to new_user_session_path,class: 'nav-link text-dark' do %>
  <button class="btn btn-md btn-light" type="submit">
   ログイン
  </button>
  <% end %>
 </li>
 <% end %>
</ul>
</div>
</div>
</nav>

    <%= yield %>
  </body>
</html>