config/routes.rb
Rails.application.routes.draw do

root to:'homes#top'

  namespace :admin do
    resources :users, only:[:index]
  end
  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end

  namespace :public do
    resources :users, only:[:show,:edit,:update,:destroy]do
      member do
    get :likes
    end
      get :search, on: :collection
      resource :relationships, only: [:create, :destroy]
        get :followings, on: :member
        get :followers, on: :member
end
end

  namespace :public do
    resources :posts, only:[:index,:new,:create,:destroy, :show]do
      resource :likes, only: [:create, :destroy]
        resources :comments, only:[:create,:destroy]
          collection do
            get 'search'
          end
    end
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leica</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/2cd9976ab2.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to public_posts_path do %>
          <div class="navbar-brand p-3"><i class="fa-solid fa-camera-retro"></i>Leicagram</div>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to new_public_post_path, class: 'nav-link text-dark' do %>
              <i class="fa-solid fa-plus"></i>投稿フォーム
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_user_path(current_user.id), class: 'nav-link text-dark' do %>
              <i class="fa-solid fa-house"></i>マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
              <i class="fa-solid fa-right-from-bracket"></i>ログアウト
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
              <i class="fa-solid fa-user-plus"></i>新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
              <i class="fa-solid fa-right-to-bracket"></i>ログイン
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
  </body>
</html>